const $=id=>document.getElementById(id), channels=['general','off-goal','erratic','conflict','outreach','deceptive','credentials'];
const labels={general:'General','off-goal':'Off-goal',erratic:'Loop / erratic',conflict:'Friction',outreach:'Outreach',deceptive:'Drift*',credentials:'Credentials*'};
// Data URL comes from the page, so a gateway can point each village at its own feed.
const FEED=document.querySelector('meta[name="heat-feed"]')?.content||'/api/live';
let data=null, mode='current', selected=null, selectedChannel='general', busy=false, drawn=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));}
function age(v){if(!v)return '—';let s=Math.max(0,(Date.now()-Date.parse(v))/1000);return s<60?Math.round(s)+'s':s<3600?Math.floor(s/60)+'m':Math.floor(s/3600)+'h';}
function time(v){return v?new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';}
function level(v,c){if(v==null)return 'No data';let t=data.dashboard.channels[c].thresholds;return v>=t.critical?'High':v>=t.hot?'Elevated':v>=t.warm?'Warm':'Below warm';}
function color(v,c){return {'No data':'#252c35','Below warm':'#203d43',Warm:'#766126',Elevated:'#9c4627',High:'#993750'}[level(v,c)];}
function hours(){const now=new Date(data.dashboard.generated_at);now.setUTCMinutes(0,0,0);return Array.from({length:24},(_,i)=>new Date(+now-(23-i)*3600000).toISOString().slice(0,16)+'Z');}
function names(){return Object.keys(data.roster).filter(a=>($('all').checked||data.roster[a].participating)&&a.toLowerCase().includes($('search').value.toLowerCase())).sort((a,b)=>a.localeCompare(b));}
function pick(a,c){selected=a;selectedChannel=c;renderMap();renderDetail();}
function cell(a,c,v,title,slot='now'){let td=document.createElement('td');td.className='cell';td.tabIndex=0;td.style.background=color(v,c);td.title=title||`${a} · ${labels[c]}: ${v??'no data'} · ${level(v,c)}`;td.innerHTML=v==null?'—':esc(Number(v).toFixed(1))+(mode==='current'?`<span class="sub">${level(v,c)}</span>`:'');td.setAttribute('aria-label',td.title);td.dataset.focus=a+'|'+c+'|'+slot;td.onclick=()=>pick(a,c);td.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick(a,c)}};return td;}
function renderMap(){if(!data?.dashboard)return;const ns=names(), c=$('channel').value, hs=hours(), table=document.createElement('table');table.className=mode==='history'?'history':'';table.innerHTML='<thead><tr><th>Agent · alphabetical</th>'+ (mode==='current'?channels.map(c=>`<th>${labels[c]}</th>`).join(''):hs.map(h=>`<th title="${esc(new Date(h).toLocaleString())}">${new Date(h).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</th>`).join(''))+'</tr></thead>';let tbody=document.createElement('tbody');for(const a of ns){let tr=document.createElement('tr');if(a===selected)tr.className='selected';let name=document.createElement('td');name.className='name';let b=document.createElement('button');b.textContent=a;b.dataset.focus='name|'+a;b.onclick=()=>pick(a,mode==='history'?c:'general');name.append(b);tr.append(name);let info=data.dashboard.agents[a];if(mode==='current'){for(const c of channels)tr.append(cell(a,c,info?.heat[c]));}else{for(const h of hs){let v=data.history.agents[a]?.heat_peak[h]?.[c];tr.append(cell(a,c,v,`${a} · ${new Date(h).toLocaleString()} · hourly peak ${v??'not observed'}`,h));}}tbody.append(tr);}table.append(tbody);const focused=document.activeElement?.closest?.('#map')&&document.activeElement.dataset.focus;$('map').replaceChildren(ns.length?table:Object.assign(document.createElement('div'),{className:'empty',textContent:'No matching agents.'}));if(focused)[...$('map').querySelectorAll('[data-focus]')].find(n=>n.dataset.focus===focused)?.focus({preventScroll:true});$('mapTitle').textContent=mode==='current'?'Current heat by channel':`24-hour heat map · ${labels[c]}`;$('mapNote').textContent=mode==='current'?'Raw heat; colors use channel-specific thresholds. Click a cell for reasons. * Drift is unvalidated; credentials is rule-based.':'Hourly peak heat, in your local time. Blank cells mean no recorded observations. Click any cell to inspect that agent’s current signal.';}
function renderDetail(){if(!selected||!data?.dashboard)return;let a=selected,c=selectedChannel,d=data.dashboard.agents[a],t=data.dashboard.channels[c].thresholds,v=d?.heat[c],reasons=(d?.contributions||[]).filter(r=>r.channel===c||r.c===c).slice(-5).reverse();let fallback=d?.reasons[c]||[];$('detail').innerHTML=`<h2 id="detailTitle">${esc(a)} <span class="pill">${esc(labels[c])}</span></h2><div id="channelNote">${esc(data.dashboard.channels[c].note)}</div><div class="metrics"><div><strong>${v==null?'—':v.toFixed(1)}</strong><span>Current heat</span></div><div><strong>${esc(level(v,c))}</strong><span>Signal level</span></div></div><div class="muted">Warm ${t.warm} · Elevated ${t.hot} · High ${t.critical}<br>Last observed event: ${esc(d?.last_event?new Date(d.last_event).toLocaleString():'Not observed in fetched window')}</div><div style="margin-top:14px;font-weight:600">Recent contributions</div>`;let box=document.createElement('div');if(reasons.length){for(let r of reasons){let row=document.createElement('div');row.className='reason';row.textContent=[r.reason||r.reasons||r.r, r.added!=null?(r.added>=0?'+':'')+r.added:'',r.when||r.time||r.t||''].filter(Boolean).join(' · ');box.append(row);}}else if(fallback.length){for(let r of fallback){let row=document.createElement('div');row.className='reason';row.textContent=r;box.append(row);}}else{box.className='muted';box.textContent='No recent contributions recorded for this channel.';}$('detail').append(box);renderEvidence(a,c,d);$('trendLabel').textContent=`${a} · ${labels[c]} · last 24 hours`;renderTrend(a,c,t);}
function renderTrend(agent,channel,thresholds){
 const hs=hours(),values=hs.map(h=>data.history.agents[agent]?.heat_peak[h]?.[channel]);
 const top=Math.ceil(Math.max(thresholds.hot,...values.filter(v=>v!=null))*1.2)||1;
 const left=52,right=430,bottom=166,upper=30,x=i=>left+i*(right-left)/23,y=v=>bottom-v/top*(bottom-upper);
 let paths=[],path='';
 values.forEach((v,i)=>{if(v==null){if(path)paths.push(path);path='';return;}path+=(path?' L':'M')+x(i)+','+y(v);});if(path)paths.push(path);
 const ticks=[0,top/2,top];
 const grid=ticks.map(v=>`<line x1="${left}" y1="${y(v)}" x2="${right}" y2="${y(v)}" stroke="#263646"/><text x="${left-9}" y="${y(v)+4}" text-anchor="end" fill="#91a3b8" font-size="16">${v.toFixed(v%1?1:0)}</text>`).join('');
 const times=($('chart').clientWidth<420?[0,12,23]:[0,8,16,23]).map(i=>`<text x="${x(i)}" y="187" text-anchor="${i===0?'start':i===23?'end':'middle'}" fill="#91a3b8" font-size="16">${23-i?23-i+'h ago':'Now'}</text>`).join('');
 const last=values.reduce((found,v,i)=>v==null?found:i,-1);
 const points=values.map((v,i)=>v==null?'':`<circle cx="${x(i)}" cy="${y(v)}" r="3" fill="#72e3bd"><title>${esc(new Date(hs[i]).toLocaleString())}: ${v.toFixed(1)} heat</title></circle>`).join('');
 const latest=last<0?'':`<text x="${x(last)}" y="${y(values[last])-10}" text-anchor="${last>20?'end':'middle'}" fill="#c9fff0" font-size="16">${values[last].toFixed(1)}</text>`;
 $('chart').innerHTML=`<svg viewBox="0 0 520 219" role="img" aria-label="${esc(labels[channel])} hourly peak heat over the last 24 hours. Vertical axis: heat points. Horizontal axis: hours ago."><text x="${left}" y="15" fill="#91a3b8" font-size="16">Heat points</text>${grid}<line x1="${left}" y1="${y(thresholds.hot)}" x2="${right}" y2="${y(thresholds.hot)}" stroke="#9c7048" stroke-dasharray="4 4"/><text x="${right+7}" y="${y(thresholds.hot)+4}" fill="#bca47d" font-size="16">Elevated ${thresholds.hot}</text>${paths.map(p=>`<path d="${p}" fill="none" stroke="#72e3bd" stroke-width="2"/>`).join('')}${points}${latest}${times}<text x="${(left+right)/2}" y="209" text-anchor="middle" fill="#91a3b8" font-size="16">Time before current hour</text></svg>`;
}

function render(){const s=data.status||{},d=data.dashboard;$("villageName").textContent=(s.village_name||"AI Village")+" · your existing Heatbot scorer";const ds=s.discord||{};$('discordStatus').textContent=ds.error?'Discord: '+ds.error:ds.enabled?'Discord enabled · '+(ds.sent||0)+' alerts sent':'Discord: disabled';const old=!s.last_success||(Date.now()-Date.parse(s.last_success)>((s.poll_seconds||60)*2+120)*1000);if(s.poll_seconds)$('pollNote').textContent=`Feed polls every ${s.poll_seconds} seconds after each fetch; view refreshes every 10 seconds.`;$('status').textContent=s.error?'Feed error · last snapshot':!s.last_success?'Warming up…':old?'Stale snapshot':s.polling?'Live · fetching':'Live · connected';$('status').className='status '+(old||s.error?'warn':'ok');$('error').textContent=s.error?'Source fetch failed. Retaining the last successful snapshot: '+s.error:'';if(!d)return;let ns=Object.keys(data.roster).filter(a=>data.roster[a].participating);$('agentCount').textContent=ns.length;$('warmCount').textContent=ns.filter(a=>data.dashboard.agents[a]?.heat.general>=d.channels.general.thresholds.warm).length;$('hotCount').textContent=ns.filter(a=>data.dashboard.agents[a]?.heat.general>=d.channels.general.thresholds.hot).length;$('eventAge').textContent=age(data.latest_event);$('updated').textContent=`Snapshot ${time(d.generated_at)} · ${new Date(d.generated_at).toLocaleDateString()} · ${age(d.generated_at)} ago`;$('feedMeta').textContent=`${data.events_in_window.toLocaleString()} source events in the fetched window · ${data.source_days_utc.join(' to ')} UTC · read-only local viewer`;if(!selected)selected=names().find(a=>d.agents[a])||names()[0];if(d.generated_at!==drawn){drawn=d.generated_at;renderMap();renderDetail();}}
async function refresh(){if(busy)return;busy=true;try{let res=await fetch(FEED,{cache:'no-store'});if(!res.ok)throw Error('HTTP '+res.status);data=await res.json();render();}catch(e){$('status').textContent='Viewer disconnected';$('status').className='status warn';$('error').textContent='The local collector is unavailable. Restart with START_HEATMAP.cmd. Last displayed values are stale.';}finally{busy=false;}}
$('channel').innerHTML=channels.map(c=>`<option value="${c}">${labels[c]}</option>`).join('');$('channel').hidden=true;
for(const m of ['current','history'])$(m+'Tab').onclick=()=>{mode=m;$('currentTab').classList.toggle('active',m==='current');$('historyTab').classList.toggle('active',m==='history');$('channel').hidden=m==='current';renderMap();};
$('search').oninput=renderMap;$('all').onchange=renderMap;$('channel').onchange=renderMap;$('refresh').onclick=refresh;refresh();setInterval(refresh,10000);
